const MAIN_MENU_SCREEN = 'MainMenuScreen'

const QUIZ_GAME_SCREEN = 'QuizGameScreen'
const QUIZ_HOME_SCREEN = 'QuizHomeScreen'
const QUIZ_START_SCREEN = 'QuizStartScreen'
const QUIZ_RESULT_SCREEN = 'QuizResultScreen'

const ANAGRAMA_START_SCREEN = 'AnagramaStartScreen'

const FORCA_START_SCREEN = 'ForcaStartScreen'

const ASSOCIACAO_START_SCREEN = 'AssociacaoStartScreen'

export {
  MAIN_MENU_SCREEN,
  QUIZ_GAME_SCREEN,
  QUIZ_START_SCREEN,
  QUIZ_HOME_SCREEN,
  QUIZ_RESULT_SCREEN,
  FORCA_START_SCREEN,
  ANAGRAMA_START_SCREEN,
  ASSOCIACAO_START_SCREEN
}
