const MAIN_MENU_SCREEN = 'MainMenuScreen'

const QUIZ_GAME_SCREEN = 'QuizGameScreen'
const QUIZ_HOME_SCREEN = 'QuizHomeScreen'
const QUIZ_START_SCREEN = 'QuizStartScreen'
const QUIZ_RESULT_SCREEN = 'QuizResultScreen'

const ANAGRAMA_START_SCREEN = 'AnagramaStartScreen'
const ANAGRAMA_GAME_SCREEN = 'AnagramaGameScreen'
const ANAGRAMA_RESULT_SCREEN = 'AnagramaResultScreen'

const FORCA_START_SCREEN = 'ForcaStartScreen'
const FORCA_GAME_SCREEN = 'ForcaGameScreen'
const FORCA_END_SCREEN = 'ForcaEndScreen'

const ASSOCIACAO_START_SCREEN = 'AssociacaoStartScreen'

export {
  MAIN_MENU_SCREEN,
  QUIZ_GAME_SCREEN,
  QUIZ_START_SCREEN,
  QUIZ_HOME_SCREEN,
  QUIZ_RESULT_SCREEN,
  FORCA_START_SCREEN,
  FORCA_GAME_SCREEN,
  FORCA_END_SCREEN,
  ANAGRAMA_START_SCREEN,
  ANAGRAMA_GAME_SCREEN,
  ANAGRAMA_RESULT_SCREEN,
  ASSOCIACAO_START_SCREEN
}
